# Stage 1: Build the Go application
FROM golang:1.22.10-alpine3.21 AS builder

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache git

# Copy the Go mod files and download dependencies
RUN go mod init app

# Build the Go application (this avoids having extra dependencies in the final image)
RUN go install github.com/steebchen/prisma-client-go@v0.45.0

# Stage 2: Create the final minimal image
FROM alpine:3.21

# Install required libraries for running Go binaries (without unnecessary build tools)
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy the schema and Go binary from the builder stage
COPY --from=builder /go/bin/prisma-client-go /usr/local/bin/
COPY prisma/schema.prisma schema.prisma

CMD ["prisma-client-go", "db", "push", "--skip-generate"]
