services:
  postgres:
    container_name: "XenoDB"
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=Xeno
      - POSTGRES_PASSWORD=Xeno
      - POSTGRES_DB=Xeno
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Xeno"]
      interval: 2s
      timeout: 1s
      retries: 5

  redis:
    container_name: "XenoRedis"
    image: redis:7.4-alpine
    restart: always
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
        test: ["CMD-SHELL", "echo 'auth ${REDIS_PASSWORD}\nping' | redis-cli | grep PONG"]
        interval: 5s
        timeout: 3s
        retries: 5

  database_sync:
    container_name: "XenoSync"
    build:
      context: .
      dockerfile: ./Dockerfile_Prisma
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  bot:
    container_name: "Xeno"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      database_sync:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      JISHAKU_HIDE: "True"
      JISHAKU_RETAIN: "True"
      JISHAKU_NO_UNDERSCORE: "True"
      JISHAKU_FORCE_PAGINATOR: "True"
      JISHAKU_NO_DM_TRACEBACK: "True"
      PYTHONUNBUFFERED: 1

volumes:
  pg_data:
  .:
  pgadmin-data:
  redis_data:
