services:
  postgres:
    container_name: "XenoDB"
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=Xeno
      - POSTGRES_PASSWORD=Xeno
      - POSTGRES_DB=Xeno
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Xeno"]
      interval: 2s
      timeout: 1s
      retries: 5
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    env_file:
      - pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  bot:
    container_name: "Xeno"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/main
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      JISHAKU_HIDE: "True"
      JISHAKU_RETAIN: "True"
      JISHAKU_NO_UNDERSCORE: "True"
      JISHAKU_FORCE_PAGINATOR: "True"
      JISHAKU_NO_DM_TRACEBACK: "True"
      PYTHONUNBUFFERED: 1

volumes:
  pg_data:
  .:
  pgadmin-data:
