[tool.poetry]
name = "xenov2"
version = "0.1.0"
description = ""
authors = ["Vahin Mehra <vahin@vahin.dev>"]
license = "AGPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.8"
asyncio = "^3.4.3"
aiohttp = "^3.11.11"
asyncpg = "^0.30.0"
cachetools = "^5.5.0"
discord-py = {extras = ["voice"], version = "^2.4.0"}
jishaku = {git = "https://github.com/Gorialis/jishaku.git"}
python-dotenv = "^1.0.1"
gitpython = "^3.1.43"
typing-extensions = "^4.12.2"
psutil = "^6.1.1"
humanfriendly = "^10.0"
python-logging-loki = "^0.3.1"
prisma = "^0.15.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
